"""add id autoinc

Revision ID: a38b50cd0a14
Revises: d6cd8852cd68
Create Date: 2023-05-11 00:42:03.145811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38b50cd0a14'
down_revision = 'd6cd8852cd68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
