"""add id autoinc in user

Revision ID: acaa293023da
Revises: a38b50cd0a14
Create Date: 2023-05-11 00:42:41.171684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acaa293023da'
down_revision = 'a38b50cd0a14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
