"""add foregin key

Revision ID: d6cd8852cd68
Revises: d6342fb576f5
Create Date: 2023-05-10 23:50:29.090724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6cd8852cd68'
down_revision = 'd6342fb576f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'party', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'party', type_='foreignkey')
    op.drop_column('party', 'owner_id')
    # ### end Alembic commands ###
