"""add invitations

Revision ID: c08522b64910
Revises: b85c2c959542
Create Date: 2023-05-18 02:32:56.820708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08522b64910'
down_revision = 'b85c2c959542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ondelete='CASCADE')
    )
    op.add_column('party', sa.Column('count_of_guests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party', 'count_of_guests')
    op.drop_table('invitations')
    # ### end Alembic commands ###
